OK. Caught an exception

PASS successfullyParsed is true

